name: weather
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  geolocator: ^7.1.0
  #  needed for API call
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  flutter_spinkit: ^5.0.0
  dart_date: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  
  assets:
    - images/AppLogo.png


  fonts:
    - family: Jomhuria
      fonts:
        - asset: fonts/Jomhuria-Regular.ttf
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto-Regular.ttf
    - family: Montserrat
      fonts: 
        - asset: fonts/Montserrat-Regular.ttf 
        
